### ISSUE TITLE
How to use this example?

### ISSUE THREAD

**Issue by azlanjamal** [jshvarts/OfflineSampleApp#6]
I tried running your code and I get 500 error? Do I need to do anything with jsonplaceholder.typicode.com such as setting up a server before I can run code on the GitHub?

**Comment by jshvarts** [comment]
It's a new issue that I have not seen before:

OkHttp: <-- 500 Internal Server Error http://jsonplaceholder.typicode.com/comments

Yet curl -v -I 'http://jsonplaceholder.typicode.com/comments' returns 200.

I can investigate when I have some time

**Comment by azlanjamal** [comment]
Any new development on this issue?

**Comment by jshvarts** [comment]
"I can investigate when I have some time" ^

This ticket will be updated after that.
